# file: postgresql/tasks/install_yum.yml

# The standard ca-certs are needed because  without them apt_key will fail to
# validate www.postgresql.org (or probably any other source).
- name: PostgreSQL | Make sure the CA certificates are available
  yum:
    name: ca-certificates
    state: present

- name: Install pgdg repository package (RedHat)
  yum: name="https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-{{ ansible_os_family | lower }}-repo-latest.noarch.rpm" state=latest

- name: PostgreSQL | Blacklist CentOS PostgreSQL packages
  replace: |
    dest=/etc/yum.repos.d/CentOS-Base.repo \
    regexp='^\[{{ item }}\]\n(?!exclude=postgresql*)' \
    replace='[{{ item }}]\nexclude=postgresql*\n'
  with_items:
    - "base"
    - "updates"

- name: PostgreSQL | Make sure the dependencies are installed
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: ["python-psycopg2", "python-pycurl", "glibc-common"]

- name: PostgreSQL | Install PostgreSQL
  yum:
    name: "{{ item }}"
    state: present
  environment: "{{ postgresql_env }}"
  with_items:
    - "postgresql{{ postgresql_version_terse }}-server"
    - "postgresql{{ postgresql_version_terse }}"
    - "postgresql{{ postgresql_version_terse }}-contrib"

- name: PostgreSQL | PGTune
  yum:
    name: pgtune
    state: present
  environment: "{{ postgresql_env }}"
  when: postgresql_pgtune

- name: PostgreSQL | pg_activity
  yum:
    name: pg_activity-1.4.0
    state: present
  environment: "{{ postgresql_env }}"
