# file: postgresql/handlers/main.yml

- name: restart postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted

- name: reload postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: reloaded
